# Generated by Django 4.2.5 on 2023-10-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="наименование")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="страна"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="дом"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
            ],
            options={
                "verbose_name": "завод",
                "verbose_name_plural": "заводы",
            },
        ),
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="наименование")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="страна"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="дом"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chain.factory",
                    ),
                ),
            ],
            options={
                "verbose_name": "розничная сеть",
                "verbose_name_plural": "розничные сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="наименование")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="модель"
                    ),
                ),
                (
                    "published",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chain.factory",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="наименование")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="страна"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="город")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="улица"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="дом"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chain.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "предприниматель",
                "verbose_name_plural": "предприниматели",
            },
        ),
    ]
