# Generated by Django 4.2.5 on 2023-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="country",
            field=models.CharField(default=1, max_length=100, verbose_name="страна"),
            preserve_default=False,
        ),
    ]
