# Generated by Django 4.2.5 on 2023-10-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chain", "0004_alter_retailer_city_alter_retailer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chain.city"
            ),
        ),
        migrations.AlterField(
            model_name="entrepreneur",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="chain.country",
            ),
            preserve_default=False,
        ),
    ]
